name: Linux Integration Builds

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  continuous-integration:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: Debug
    strategy:
      fail-fast: false
      matrix:
        # specify a specific compiler to build with each OS separately
        include:
          - platform_name: linux
            os: ubuntu-20.04
            cxx: g++-11
          ## NOTE: CXX seems to be ignored on Windows, but specify it anyway for consistency
          #- platform_name: windows
          #  os: windows-2019
          #  cxx: msvc
          #  cmake_generator: ""

    steps:
      - uses: actions/checkout@v2

      - name: Get Ubuntu updates
        if: runner.os == 'Linux'
        run: sudo apt-get update

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt install -y wx3.0-headers wx-common libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev libwxbase3.0-dev build-essential libtool automake autoconf libgtk-3-dev libboost-dev libboost-system-dev libhunspell-dev libgamin-dev 

      - name: Shell Permission Update
        working-directory: ${{github.workspace}}/Build_Helper_Files/CodeBlocks_Linux
        shell: bash
        run: chmod +x *.sh

      - name: Change Permissions
        working-directory: ${{github.workspace}}/Build_Helper_Files/CodeBlocks_Linux
        shell: bash
        run: ./change_permissions_Linux.sh

      - name: Build CodeBlocks
        working-directory: ${{github.workspace}}/Build_Helper_Files/CodeBlocks_Linux
        shell: bash
        run: ./codeblocks_build.sh
